name: pages
on:
  workflow_dispatch:
  push:
    branches: [main]
permissions:
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT_TOKEN }}

    - name: Bun
      uses: oven-sh/setup-bun@v2

    - name: FFmpeg
      run: sudo apt-get install -y ffmpeg

    - name: AudioWaveform
      run: |
        sudo add-apt-repository ppa:chris-needham/ppa
        sudo apt-get install audiowaveform

    - name: Build
      run: |
        git lfs pull
        bun i
        bun build.ts

    - name: Configure
      uses: actions/configure-pages@v4

    - name: Upload
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'public'

    - name: Deploy
      uses: actions/deploy-pages@v4
      id: deployment
